import type { Metadata } from "next";
import "./globals.css";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Trappin NYC Database Manager",
  description: "Generated by Left",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(
        "h-screen bg-background font-sans antialiased dark overflow-hidden",
        fontSans.variable
      )}
      >
        <div className="relative flex flex-col bg-background container py-6 overflow-hidden h-full">{children}</div>
      </body>
    </html>
  );
}
